#!/usr/bin/python
import platform
import subprocess
import sys

if platform.system() == "Darwin":
    path = "/usr/local/bin/mvim"
else:
    path = "/usr/bin/mvim"

args = [str(x) for x in sys.argv[1:]]
subprocess.call([path, "-u", " ~/VIM/portable-vim"] + args)
