#!/usr/bin/python3
import platform
import subprocess
import sys

if platform.system() == "Darwin":
    path = "/usr/local/bin/vim"
else:
    path = "/usr/bin/vim"

args = [str(x) for x in sys.argv[1:]]
subprocess.call([path, "-u", " ~/VIM/portable-vim"] + args)
