# -*- mode: ruby -*-
# vi: set ft=ruby :

# Structure : 
# - provisioning
#    - roles
#        - role
#           - files
#           - handlers
#             - main.yml
#           - meta
#             - main.yml
#           - tasks
#             - main.yml
#           - templates
#           - vars
#             - main.yml
#    - inventory
#    - playbook.yml
# - Vagrantfile
#

box      = "trusty64"
url      = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
domain   = "cbalan.com"
ram      = "1024"

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box       = box
  config.vm.box_url   = url

  config.vm.define :phabricator do |cfg|
    cfg.vm.network :private_network, ip: "192.168.0.100"
    cfg.vm.host_name = "phabricator" + '.' + domain
    cfg.vm.provider :virtualbox do |vbox|
      vbox.customize ["modifyvm", :id, "--name", "phabricator"]
      vbox.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vbox.customize ["modifyvm", :id, "--memory", ram]
    end
  end

  config.vm.define :devserver do |cfg|
    cfg.vm.network :private_network, ip: "192.168.0.200"
    cfg.vm.host_name = "devserver" + '.' + domain
    cfg.vm.provider :virtualbox do |vbox|
      vbox.customize ["modifyvm", :id, "--name", "devserver"]
      vbox.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vbox.customize ["modifyvm", :id, "--memory", ram]
    end
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/playbook.yml"
    ansible.inventory_path = "provisioning/inventory"
    ansible.sudo = true
    ansible.groups = {
      "phabricators" => ["phabricator"],
      "devservers" => ["devserver"],
      "all" => ["phabricators", "devservers"],
    }
  end

end
