---
- name: Update System
  apt: upgrade=full update-cache=yes

- name: Install x86 libs
  apt: pkg={{ item }} state=installed update_cache=true
  with_items:
    - libc6-i386
    - lib32stdc++6
    - lib32gcc1
    - lib32ncurses5
    - lib32z1

- name: Install XServer
  apt: pkg={{ item }} state=installed update_cache=true
  with_items:
    - xvfb

#- name: Start XServer
#  command:  Xvfb :1 -screen 0 1024x768x24 &
#  sudo: no

- name: Install Basics
  apt: pkg={{ item }} state=installed update_cache=true
  with_items:
    - wget
    - vim
    - ctags
    - git
    - subversion
    - python-dev
    - g++
    - clang-3.5
    - make
    - cmake
    - cgdb
    - silversearcher-ag

- name: Install Java and Scala
  apt: pkg={{ item }} state=installed update_cache=true
  with_items:
    - openjdk-7-jdk
    - scala
    - ant
    - maven

# Create SwapFile
- name: Copy swap file script
  copy: src=createSwapFile.sh dest=/home/vagrant owner=vagrant mode=0755
- name: Execute swap file script
  command: /home/vagrant/createSwapFile.sh
- name: Delete swap file script
  command: rm /home/vagrant/createSwapFile.sh

# Install Vim
- name: Clone VIM
  git: repo=https://github.com/Cosmin1490/VIM dest=/home/vagrant/VIM
  sudo: no
- name: Touch cbalan_vim_first_time
  command: touch cbalan_vim_first_time
  sudo: no
#- name: Download Vim Plugins
#  command: /home/vagrant/VIM/lots/vvim "+NeoBundleInstall" "+qall"
#  sudo: no
- name: remove cbalan_vim_first_time
  command: rm cbalan_vim_first_time
  sudo: no

# Install Eclipse
- name: Download Eclipse
  command: wget http://ftp.osuosl.org/pub/eclipse/technology/epp/downloads/release/mars/R/eclipse-java-mars-R-linux-gtk-x86_64.tar.gz
  sudo: no
- name: Untar Eclipse
  command: tar -xzf eclipse-java-mars-R-linux-gtk-x86_64.tar.gz
  sudo: no
- name: Remove Eclipse tar
  command: rm eclipse-java-mars-R-linux-gtk-x86_64.tar.gz
  sudo: no

# Install Eclim
- name: Copy installEclim.sh script
  copy: src=installEclim.sh dest=/home/vagrant owner=vagrant mode=0755
  sudo: no
- name: Clone Eclim
  command: git clone https://github.com/ervandew/eclim
  sudo: no
- name: Install Eclipse Plugins
  command: ./installEclim.sh
  sudo: no
- name: Install Eclim Eclipse
  command: chdir=/home/vagrant/eclim ant deploy.eclipse -Declipse.home=/home/vagrant/eclipse
  sudo: no
- name: Install Eclim Vim
  command: chdir=/home/vagrant/eclim ant deploy.vim -Dvim.files=/home/vagrant/.vim -Declipse.home=/home/vagrant/eclipse
  sudo: no


