---
- name: Update System
  apt: upgrade=full update-cache=yes

- name: Install Basics
  apt: pkg={{ item }} state=installed update_cache=true
  with_items:
    - wget
    - vim
    - ctags
    - git
    - subversion
    - python-dev
    - g++
    - clang-3.5
    - make
    - cmake

- name: Install Java and Scala
  apt: pkg={{ item }} state=installed update_cache=true
  with_items:
    - openjdk-7-jdk
    - scala
    - ant
    - maven

- name: Install XServer
  apt: pkg={{ item }} state=installed update_cache=true
  with_items:
    - xvfb

#- name: Start XServer
#  command:  Xvfb :1 -screen 0 1024x768x24 &
#  sudo: no

- name: Copy swap file script
  copy: src=createSwapFile.sh dest=/home/vagrant owner=vagrant mode=0755
- name: Execute swap file script
  command: /home/vagrant/createSwapFile.sh
- name: Delete swap file script
  command: rm /home/vagrant/createSwapFile.sh

- name: Clone VIM
  git: repo=https://github.com/Cosmin1490/VIM dest=/home/vagrant/VIM
  sudo: no

#- name: Set Up Environment Variables
#- name: Install Vim Plugins
#- name: Compile YCM
#- name: Setup Eclipse and Eclim
