---
- name: Install Basics
  apt: pkg={{ item }} state=installed update_cache=true
  with_items:
    - wget
    - vim
    - ctags
    - git
    - svn
    - python-dev
    - g++
    - make
    - cmake

