---
- name: Update System
  apt: upgrade=full update-cache=yes

- name: Install Basics
  apt: pkg={{ item }} state=installed update_cache=true
  with_items:
    - wget
    - vim
    - ctags
    - git
    - subversion
    - python-dev
    - g++
    - clang-3.5
    - make
    - cmake

- name: Install Java and Scala
  apt: pkg={{ item }} state=installed update_cache=true
  with_items:
    - openjdk-7-jdk
    - scala
    - ant
    - maven

- name: Install XServer
  apt: pkg={{ item }} state=installed update_cache=true
  with_items:
    - xvfb

#- name: Start XServer
#  command:  Xvfb :1 -screen 0 1024x768x24 &
#  sudo: no

# Create SwapFile
- name: Copy swap file script
  copy: src=createSwapFile.sh dest=/home/vagrant owner=vagrant mode=0755
- name: Execute swap file script
  command: /home/vagrant/createSwapFile.sh
- name: Delete swap file script
  command: rm /home/vagrant/createSwapFile.sh

# Install Eclipse
- name: Download eclipse-luna-standard
  command: wget http://mirrors.ibiblio.org/pub/mirrors/eclipse/technology/epp/downloads/release/luna/R/eclipse-standard-luna-R-linux-gtk.tar.gz
  sudo: no
- name: Untar eclipse
  command: tar -xzf eclipse-standard-luna-R-linux-gtk.tar.gz
  sudo: no
- name: Remove eclipse tar
  command: rm eclipse-standard-luna-R-linux-gtk.tar.gz
  sudo: no

# Install Vim
- name: Clone VIM
  git: repo=https://github.com/Cosmin1490/VIM dest=/home/vagrant/VIM
  sudo: no
- name: Touch cbalan_vim_first_time
  command: touch cbalan_vim_first_time
  sudo: no
- name: Download Vim Plugins
  command: /home/vagrant/VIM/lots/vvim "+PluginInstall" "+qall"
  sudo: no
- name: remove cbalan_vim_first_time
  command: rm cbalan_vim_first_time
  sudo: no
- name: Compile YCM
  command: chdir=/home/vagrant/VIM ./compileYcm.sh

#- name: Set Up Environment Variables
#- name: Eclim
